runtime: python39

env_variables:
  FLASK_ENV: "production"

handlers:
  # Static files
  - url: /static
    static_dir: app/static
    secure: always

  # Logos directory
  - url: /logos
    static_dir: Logos
    secure: always

  # All other URLs
  - url: /.*
    script: auto
    secure: always

# Automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1

# Instance class (F1 = smallest, cheapest)
instance_class: F1
