"""Add Organization model and multi-tenant support

Revision ID: 302bd15b682a
Revises: ba4b074f7e95
Create Date: 2026-01-28 11:24:12.882393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302bd15b682a'
down_revision = 'ba4b074f7e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=True),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('icone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('assinatura_nome', sa.String(length=100), nullable=True),
    sa.Column('assinatura_cargo', sa.String(length=100), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    with op.batch_alter_table('certificate_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizacao_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_certificate_templates_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_foreign_key('fk_certificate_templates_organizacao', 'organizations', ['organizacao_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizacao_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_organizacao_id'), ['organizacao_id'], unique=False)
        batch_op.create_foreign_key('fk_events_organizacao', 'organizations', ['organizacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_organizacao', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_organizacao_id'))
        batch_op.drop_column('organizacao_id')

    with op.batch_alter_table('certificate_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_certificate_templates_organizacao', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_certificate_templates_organizacao_id'))
        batch_op.drop_column('organizacao_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
