"""Make data_inicio nullable in events table

Revision ID: af1ac7450652
Revises: f2971c7ea6b4
Create Date: 2026-02-06 23:18:22.354659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1ac7450652'
down_revision = 'f2971c7ea6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Simply make data_inicio nullable
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert data_inicio to not nullable
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
