"""Rename duracao_horas to duracao_minutos

Revision ID: ba4b074f7e95
Revises: b41022b26364
Create Date: 2026-01-17 21:05:14.812039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4b074f7e95'
down_revision = 'b41022b26364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add new column as nullable
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao_minutos', sa.Integer(), nullable=True))

    # Step 2: Copy data from duracao_horas to duracao_minutos  (hours * 60 = minutes)
    op.execute('UPDATE events SET duracao_minutos = duracao_horas * 60')

    # Step 3: Make column NOT NULL
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('duracao_minutos', nullable=False)
        batch_op.drop_column('duracao_horas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao_horas', sa.INTEGER(), nullable=False))
        batch_op.drop_column('duracao_minutos')

    # ### end Alembic commands ###
