"""Add SMTP configuration to organizations

Revision ID: f2971c7ea6b4
Revises: 302bd15b682a
Create Date: 2026-01-28 11:37:54.184270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2971c7ea6b4'
down_revision = '302bd15b682a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add SMTP configuration fields to organizations table
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('smtp_password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('smtp_server', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove SMTP configuration fields from organizations table
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_server')
        batch_op.drop_column('smtp_password')
        batch_op.drop_column('smtp_email')

    # ### end Alembic commands ###
